---
# This role installs some of nitter's dependencies and creates the user
# nitter will run under

- name: Install some nitter dependencies
  ansible.builtin.apt: name={{ packages }} state=present update_cache=yes
  vars:
    packages:
      - libsass-dev
      - redis-server
      - build-essential
      - git
      - curl
      - pwgen
- name: Add the user that nitter will run as
  ansible.builtin.user: name={{ NITTER_USER }} shell=/bin/bash state=present
