---
# Download Nitter application from Github

- name: Checkout nitter repo
  ansible.builtin.git:
    repo: 'https://github.com/zedeus/nitter'
    dest: "/home/{{ NITTER_USER }}/nitter"
    force: yes
  become: true
  become_user: "{{ NITTER_USER }}"
- name: Template and copy nitter build script
  ansible.builtin.template:
    src: buildnitter.sh
    dest: "/home/{{ NITTER_USER }}/buildnitter.sh"
  become: true
  become_user: "{{ NITTER_USER }}"
- name: Run nitter build script
  ansible.builtin.shell: "bash /home/{{ NITTER_USER }}/buildnitter.sh"
  args:
    executable: /bin/bash
  become: true
  become_user: "{{ NITTER_USER }}"
